# Generated by Django 3.2.25 on 2024-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0002_auto_20240525_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
