# Generated by Django 3.2.25 on 2024-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0003_auto_20240525_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
    ]
