# Generated by Django 3.2.25 on 2024-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0005_auto_20240525_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема доклада')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('telegram_id', models.CharField(max_length=50, verbose_name='Telegram ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
