# Generated by Django 3.2.25 on 2024-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0006_newspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
