# Generated by Django 3.2.25 on 2024-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0007_speaker_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True, verbose_name='Telegram ID')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
