# Generated by Django 3.2.25 on 2024-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0008_listener'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to='event_models.Listener', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='question',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID слушателя'),
        ),
    ]
