# Generated by Django 3.2.25 on 2024-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0009_auto_20240526_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
