# Generated by Django 3.2.25 on 2024-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_models', '0010_question_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
        migrations.AddField(
            model_name='listener',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
    ]
